import {
  AccessIcon,
  Add01Icon,
  Alert02Icon,
  AndroidIcon,
  ApiIcon,
  AppleIcon,
  ArrowDown01Icon,
  ArrowLeft01Icon,
  ArrowRight01Icon,
  ArrowUp01Icon,
  ArrowUpDownIcon,
  BotIcon,
  BriefcaseBusinessIcon,
  Building02Icon,
  BulbIcon,
  Calendar01Icon,
  Call02Icon,
  Cancel01Icon,
  ChartBarLineIcon,
  ChartLineData01Icon,
  CheckmarkCircle01Icon,
  Clock01Icon,
  CloudDownloadIcon,
  CloudUploadIcon,
  ComputerChartUpIcon,
  ComputerIcon,
  CreditCardIcon,
  DashboardCircleAddIcon,
  DashboardSquare01Icon,
  Delete02Icon,
  File01Icon,
  FilterIcon,
  Flag01Icon,
  FolderOpenIcon,
  GitCompareIcon,
  Globe02Icon,
  GridIcon,
  Key01Icon,
  Layout01Icon,
  Link01Icon,
  LinkSquare02Icon,
  Loading03Icon,
  Location01Icon,
  LockPasswordIcon,
  Logout03Icon,
  Mail01Icon,
  MapsLocation01Icon,
  Megaphone01Icon,
  Menu01Icon,
  Message01Icon,
  More01Icon,
  MoreHorizontalIcon,
  Note01Icon,
  Package01Icon,
  PaintBoardIcon,
  PencilEdit01Icon,
  RefreshIcon,
  Rocket01Icon,
  Search01Icon,
  SecurityCheckIcon,
  Settings03Icon,
  Share01Icon,
  ShoppingCart01Icon,
  SmartPhone01Icon,
  SparklesIcon,
  Store01Icon,
  Tag01Icon,
  TextFontIcon,
  Tick02Icon,
  TruckIcon,
  Unlink01Icon,
  UserAdd01Icon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMinus01Icon,
  UserSharingIcon,
  ViewIcon,
  ViewOffSlashIcon,
  WhatsappIcon,
  Wrench01Icon,
} from "@hugeicons/core-free-icons";

import { createAppIcon, type TAppIconComponent } from "@/components/ui/app-icon";

/**
 * Shared Hugeicons (free Stroke Rounded) components for Crawllex chrome.
 * Prefer these over importing `@hugeicons/core-free-icons` at call sites.
 */
export const Icons = {
  access: createAppIcon(AccessIcon),
  add: createAppIcon(Add01Icon),
  alert: createAppIcon(Alert02Icon),
  analytics: createAppIcon(ComputerChartUpIcon),
  android: createAppIcon(AndroidIcon),
  api: createAppIcon(ApiIcon),
  apple: createAppIcon(AppleIcon),
  arrowDown: createAppIcon(ArrowDown01Icon),
  arrowLeft: createAppIcon(ArrowLeft01Icon),
  arrowRight: createAppIcon(ArrowRight01Icon),
  arrowUp: createAppIcon(ArrowUp01Icon),
  arrowUpDown: createAppIcon(ArrowUpDownIcon),
  bot: createAppIcon(BotIcon),
  briefcase: createAppIcon(BriefcaseBusinessIcon),
  building: createAppIcon(Building02Icon),
  bulb: createAppIcon(BulbIcon),
  calendar: createAppIcon(Calendar01Icon),
  call: createAppIcon(Call02Icon),
  cancel: createAppIcon(Cancel01Icon),
  cart: createAppIcon(ShoppingCart01Icon),
  chartBar: createAppIcon(ChartBarLineIcon),
  chartLine: createAppIcon(ChartLineData01Icon),
  checkCircle: createAppIcon(CheckmarkCircle01Icon),
  clock: createAppIcon(Clock01Icon),
  cloudDownload: createAppIcon(CloudDownloadIcon),
  cloudUpload: createAppIcon(CloudUploadIcon),
  computer: createAppIcon(ComputerIcon),
  creditCard: createAppIcon(CreditCardIcon),
  dashboard: createAppIcon(DashboardCircleAddIcon),
  dashboardSquare: createAppIcon(DashboardSquare01Icon),
  delete: createAppIcon(Delete02Icon),
  file: createAppIcon(File01Icon),
  filter: createAppIcon(FilterIcon),
  flag: createAppIcon(Flag01Icon),
  folderOpen: createAppIcon(FolderOpenIcon),
  gitCompare: createAppIcon(GitCompareIcon),
  globe: createAppIcon(Globe02Icon),
  grid: createAppIcon(GridIcon),
  key: createAppIcon(Key01Icon),
  layout: createAppIcon(Layout01Icon),
  link: createAppIcon(Link01Icon),
  linkSquare: createAppIcon(LinkSquare02Icon),
  list: createAppIcon(Menu01Icon),
  loading: createAppIcon(Loading03Icon),
  location: createAppIcon(Location01Icon),
  lock: createAppIcon(LockPasswordIcon),
  logout: createAppIcon(Logout03Icon),
  mail: createAppIcon(Mail01Icon),
  maps: createAppIcon(MapsLocation01Icon),
  megaphone: createAppIcon(Megaphone01Icon),
  message: createAppIcon(Message01Icon),
  more: createAppIcon(More01Icon),
  moreHorizontal: createAppIcon(MoreHorizontalIcon),
  note: createAppIcon(Note01Icon),
  package: createAppIcon(Package01Icon),
  paintBoard: createAppIcon(PaintBoardIcon),
  pencil: createAppIcon(PencilEdit01Icon),
  refresh: createAppIcon(RefreshIcon),
  rocket: createAppIcon(Rocket01Icon),
  search: createAppIcon(Search01Icon),
  security: createAppIcon(SecurityCheckIcon),
  settings: createAppIcon(Settings03Icon),
  share: createAppIcon(Share01Icon),
  smartphone: createAppIcon(SmartPhone01Icon),
  sparkles: createAppIcon(SparklesIcon),
  store: createAppIcon(Store01Icon),
  tag: createAppIcon(Tag01Icon),
  text: createAppIcon(TextFontIcon),
  tick: createAppIcon(Tick02Icon),
  truck: createAppIcon(TruckIcon),
  unlink: createAppIcon(Unlink01Icon),
  user: createAppIcon(UserIcon),
  userAdd: createAppIcon(UserAdd01Icon),
  userCircle: createAppIcon(UserCircleIcon),
  userGroup: createAppIcon(UserGroupIcon),
  userMinus: createAppIcon(UserMinus01Icon),
  userSharing: createAppIcon(UserSharingIcon),
  view: createAppIcon(ViewIcon),
  viewOff: createAppIcon(ViewOffSlashIcon),
  whatsapp: createAppIcon(WhatsappIcon),
  wrench: createAppIcon(Wrench01Icon),
} as const satisfies Record<string, TAppIconComponent>;

export type TIconName = keyof typeof Icons;
